# Smart watering system
# Written by Whyer


esphome:
  name: smart-sprinkler-system
  friendly_name: Smart Sprinkler System

esp32:
  board: node32s
# nodemcu-32s 
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lpu9NggS330909Hr15/hrYVL9jExWw6HgaV8el8XeCQ="

ota:
  password: "8e7ca47fb50a532b554878c84121ac05"

#
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
#    manual_ip:
#      static_ip: $staticip
#      gateway: 192.168.2.1
#      subnet: 255.255.255.0
#
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Sprinkler-System"
    password: "K5I1RCLfqkdD"

captive_portal:
web_server:
  port: 80
#
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
#
#Zone Relay 1
switch:
  - platform: gpio
    pin: 23
    inverted: true
    name: "Zone 1"
    id: zone1
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 2
  - platform: gpio
    pin: 22
    inverted: true
    name: "Zone 2"
    id: zone2
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 3
  - platform: gpio
    pin: 21
    inverted: true
    name: "Zone 3"
    id: zone3
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 4
  - platform: gpio
    pin: 19
    inverted: true
    name: "Zone 4"
    id: zone4
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 5
  - platform: gpio
    pin: 18
    inverted: true
    name: "Zone 5"
    id: zone5
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 6
  - platform: gpio
    pin: 5
    inverted: true
    name: "Zone 6"
    id: zone6
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 7
  - platform: gpio
    pin: 17
    inverted: true
    name: "Zone 7"
    id: zone7
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#Zone Relay 8
  - platform: gpio
    pin: 16
    inverted: true
    name: "Zone 8"
    id: zone8
    internal: false
#true makes the switch not show up in home assistant
    restore_mode: RESTORE_DEFAULT_OFF
#